AA_names = {	
				"Ala" : "Ala",
				"Alanine" : "Ala",
				"Arg" : "Arg",
				"Arginine" : "Arg",
				"Asn" : "Asn",
				"Asparagine" : "Asn",
				"Asp" : "Asp",
				"Aspartic Acid" : "Asp",
				"Cys" : "Cys",
				"Cysteine" : "Cys",
				"Gln" : "Gln",
				"Glutamine" : "Gln",
				"Gly" : "Gly",
				"Glycine" : "Gly",
				"His" : "His",
				"Histidine" : "His",
				"Ile" : "Ile/Leu",
				"Isoleucine" : "Ile/Leu",
				"Leu" : "Ile/Leu",
				"Leucine" : "Leu",
				"Lys" : "Lys",
				"Lysine" : "Lys",
				"Met" : "Met",
				"Methionine" : "Met",
				"Phe" : "Phe",
				"Phenylalanine" : "Phe",
				"Pro" : "Pro",
				"Proline" : "Pro",
				"Ser" : "Ser",
				"Serine": "Ser",
				"Thr" : "Thr",
				"Threonine" : "Thr",
				"Sec" : "Sec",
				"Selenocysteine" : "Sec",
				"Trp" : "Trp",
				"Tryptophan" : "Trp",
				"Tyr" : "Tyr",
				"Tyrosine" : "Tyr",
				"Val" : "Val",
				"Valine" : "Val"
			}
			
AA_alphabet = set([value for key, value in AA_names.items()])